import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup"],
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.*",
        "src/**/*.stories.*",
        "src/env.d.ts",
        "src/types.d.ts",
        "src/pi-app-test-helper.ts",
        "src/api.ts",
        "src/file-tree-model.ts",
        "src/renderers.ts",
        "src/components/WorkspaceFileTree.tsx",
        "src/pi-app/attachment-methods.ts",
        "src/pi-app/fallback-choices.ts",
        "src/pi-app/file-editor.ts",
        "src/pi-app/file-preview-methods.ts",
        "src/pi-app/layout-methods.ts",
        "src/pi-app/message-methods.ts",
        "src/pi-app/runtime-status-methods.ts",
        "src/pi-app/settings-methods.ts",
        "src/pi-app/toast-methods.ts",
        "src/pi-app/tool-output-rendering.ts",
        "src/pi-app/transcript-virtual-scroller.ts",
        "src/pi-app/transcript-window-methods.ts",
        "src/pi-app/version-methods.ts",
        "src/pi-app/workspace-bootstrap-methods.ts",
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
