import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup"],
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.*",
        "src/**/*.stories.*",
        "src/env.d.ts",
        "src/types.d.ts",
        "src/pi-app/test-helper.ts",
        "src/lib/api.ts",
        "src/lib/file-tree-model.ts",
        "src/lib/renderers.ts",
        "src/components/WorkspaceFileTree.tsx",
        "src/pi-app/input/attachment-methods.ts",
        "src/pi-app/input/fallback-choices.ts",
        "src/pi-app/editor/file-editor.ts",
        "src/pi-app/editor/file-preview-methods.ts",
        "src/pi-app/status/layout-methods.ts",
        "src/pi-app/messages/message-methods.ts",
        "src/pi-app/status/runtime-status-methods.ts",
        "src/pi-app/workspace/settings-methods.ts",
        "src/pi-app/workspace/oauth-methods.ts",
        "src/pi-app/status/toast-methods.ts",
        "src/pi-app/messages/tool-output-rendering.ts",
        "src/pi-app/transcript/transcript-virtual-scroller.ts",
        "src/pi-app/transcript/transcript-window-methods.ts",
        "src/pi-app/status/version-methods.ts",
        "src/pi-app/workspace/workspace-bootstrap-methods.ts",
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
